### ISSUE TITLE
OpenUPM related issues

### ISSUE THREAD

**Issue by favoyang** [hajimeku/ServiceLocator#1]
Hi @hajimeku,

Thanks for contributing to OpenUPM. A few issues:

- Please add an asmdef file to the package root path, see https://docs.unity3d.com/Manual/cus-asmdef.html. Learn more about it at https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html
- In general I suggest test your upm branch, before creating an release. Move the package to Packages/package-name, will make it much easier (behaves as a local package).
- I suggest add some information to README for usages.
- After all of above, please create release to match the version of package.json. In your case, please re-tag the GitHub Release v1.0 to v1.0.0. The OpenUPM build pipelines ignores non-semver tags.

**Comment by hajimeku** [comment]
Thanks for the feedback favoyang.
I added everything except for readme. It will come later.

**Comment by favoyang** [comment]
@hajimeku 

Your package looks good. The v1.0.0 has been processed successfully right after you re-tagging it. https://openupm.com/packages/com.apollo.servicelocator/

I've added PR #2 for the skeleton README (installation options + badge).
